version: '3.9'

services:
  # client:
  #   image: client
  #   build:
  #     context: ../client
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    hostname: localhost
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "newUser:1:1"
    depends_on:
      - zookeeper

  auth_service:
    image: auth_service
    build:
      context: ./Services/auth
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5001:5001"
    depends_on:
      - kafka

  checklist_service:
    image: checklist_service
    build:
      context: ./Services/checklist
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5002:5002"
    depends_on:
      - kafka

  kanbanboard_service:
    image: kanbanboard_service
    build:
      context: ./Services/kanbanboard
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5003:5003"
    depends_on:
      - kafka

  pomodoro_service:
    image: pomodoro_service
    build:
      context: ./Services/pomodoro
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5004:5004"
    depends_on:
      - kafka

  notify_service:
    image: notify_service
    build:
      context: ./Services/notification
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5005:5005"
    depends_on:
      - kafka
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"

  # redis:
  #   image: redis
  #   restart: always
  #   ports:
      # - "6379:6379"

  Nginx:
    image: nginx
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro