version: '3.9'

services:
  server:
    image: server
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    ports:
    - "4000:4000"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
