version: '3.9'

services:

  client:
    image: client
    build:
      context: ../client
      dockerfile: Dockerfile
    restart: always
    ports:
    - "3000:3000"

  server:
    image: server
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    ports:
    - "4000:4000"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
