name: "Push to DockerHub"

on:
  push:
    branches:
      - main
      - testing
    paths:
      - "Services/**"

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Services
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push - auth
        uses: docker/build-push-action@v5
        with:
          context: Services/auth
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timeshaasan-auth:${{ github.ref == 'refs/heads/main' && 'latest' || 'testing' }}

      - name: Build and push - checklist
        uses: docker/build-push-action@v5
        with:
          context: Services/checklist
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timeshaasan-checklist:${{ github.ref == 'refs/heads/main' && 'latest' || 'testing' }}

      - name: Build and push - pomodoro
        uses: docker/build-push-action@v5
        with:
          context: Services/pomodoro
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timeshaasan-pomodoro:${{ github.ref == 'refs/heads/main' && 'latest' || 'testing' }}

      - name: Build and push - kanbanboard
        uses: docker/build-push-action@v5
        with:
          context: Services/kanbanboard
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timeshaasan-kanbanboard:${{ github.ref == 'refs/heads/main' && 'latest' || 'testing' }}

      - name: Build and push - notification
        uses: docker/build-push-action@v5
        with:
          context: Services/notification
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/timeshaasan-notify:${{ github.ref == 'refs/heads/main' && 'latest' || 'testing' }}

      - name: Is it done?
        run: echo "All services are deployed on docker"
